In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#if open via google collab
from google.colab import drive 
drive.mount('/content/gdrive')
customer_profiles_table=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/project_sebastien/data/customer_profiles_table.csv")
transactions_df=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/project_sebastien/data/transactions_df.csv")
terminal_profiles_table=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/project_sebastien/data/terminal_profiles_table.csv")

In [ ]:
customer_profiles_table=pd.read_csv("./data/")
transactions_df=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/project_sebastien/data/transactions_df.csv")
terminal_profiles_table=pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/project_sebastien/data/terminal_profiles_table.csv")

In [ ]:
df

    Unnamed: 0  CUSTOMER_ID  ...  available_terminals  nb_terminals
0            0            0  ...             [29, 87]             2
1            1            1  ...                  [5]             1
2            2            2  ...                   []             0
3            3            3  ...             [65, 94]             2
4            4            4  ...                   []             0
5            5            5  ...                 [79]             1
6            6            6  ...                   []             0
7            7            7  ...                   []             0
8            8            8  ...              [8, 46]             2
9            9            9  ...                 [84]             1
10          10           10  ...                   []             0
11          11           11  ...                 [44]             1
12          12           12  ...                   []             0
13          13           13  ...                   []             0
14          14           14  ...             [88, 90]             2
15          15           15  ...              [2, 55]             2
16          16           16  ...                  [3]             1
17          17           17  ...                   []             0
18          18           18  ...                 [34]             1
19          19           19  ...                 [24]             1
20          20           20  ...                   []             0
21          21           21  ...                   []             0
22          22           22  ...             [65, 99]             2
23          23           23  ...                   []             0
24          24           24  ...             [66, 74]             2
25          25           25  ...             [17, 88]             2
26          26           26  ...                   []             0
27          27           27  ...                   []             0
28          28           28  ...             [17, 88]             2
29          29           29  ...         [40, 48, 62]             3
30          30           30  ...                   []             0
31          31           31  ...              [8, 46]             2
32          32           32  ...             [17, 88]             2
33          33           33  ...                 [64]             1
34          34           34  ...                 [29]             1
35          35           35  ...             [38, 51]             2
36          36           36  ...                   []             0
37          37           37  ...                 [54]             1
38          38           38  ...             [78, 93]             2
39          39           39  ...                   []             0
40          40           40  ...                 [31]             1
41          41           41  ...                 [79]             1
42          42           42  ...                   []             0
43          43           43  ...                 [82]             1
44          44           44  ...                   []             0
45          45           45  ...                 [93]             1
46          46           46  ...             [34, 52]             2
47          47           47  ...             [17, 41]             2
48          48           48  ...                   []             0
49          49           49  ...                 [26]             1

[50 rows x 9 columns]